/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClientController;
import Controller.OrderController;
import Controller.ProductController;
import Model.Client;
import Model.Order;
import Model.Product;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iyed
 */
public class MakeOrder extends javax.swing.JInternalFrame {

    /**
     * Creates new form Import
     */
    public MakeOrder() {
        initComponents();
         GetToday();
         TxtOrderId.setEnabled(false);
        
        ArrayList<Product>  myproductlist = new ProductController().retrieveAll();
        DefaultTableModel model = new DefaultTableModel() ;
        productList.setModel(model) ; 
        model.addColumn("idPro");
        model.addColumn("namePro");
        model.addColumn("category");
        model.addColumn("quantity");
        model.addColumn("price");
       

        for (Product p : myproductlist) {            
            Object[] row =   new Object[]{p.getIdPro(), p.getNamePro(), p.getCategorie(), p.getQte(), p.getPrice() };
            model.addRow(  row);
        }
        productList.setModel(model);
        /////////////////////////////////////
        ArrayList<Client>  myclientlist = new ClientController().retrieveAll();
        DefaultTableModel model1 = new DefaultTableModel() ;
        jTable1.setModel(model1) ; 
        model1.addColumn("IdCl");
        model1.addColumn("NameCl");
        model1.addColumn("PhoneCl");
      

        for (Client c  : myclientlist) {            
            Object[] row =   new Object[]{c.getIdCl(), c.getNameCl(),c.getPhoneCl()};
            model1.addRow(  row);
        }
        jTable1.setModel(model1);
        
    }
    public void refresh()
    {
        TxtOrderId.setText("");
        TxtNameClient.setText("");
        TxtProductName.setText("");
        TxtPrice.setText("");
        TxtQuantity.setText("");
        totallbl.setText("");
    }
    public void GetToday()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        datelbl.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        productList = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        TxtOrderId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtNameClient = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtProductName = new javax.swing.JTextField();
        AddButn = new com.k33ptoo.components.KButton();
        AddButn1 = new com.k33ptoo.components.KButton();
        jLabel16 = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtQuantity = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Import");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 95, 134));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selling Management");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/money_bag_y8voit0gtqim_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(15, 95, 134));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 430, 300));

        productList.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productList.setDragEnabled(true);
        productList.setOpaque(false);
        productList.setSelectionBackground(new java.awt.Color(15, 95, 134));
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 520, 300));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Products List");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Client List");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        jPanel1.add(TxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 120, 30));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Order Id");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        datelbl.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        datelbl.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, -1, 30));

        TxtOrderId.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(TxtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, 30));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Client Name ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));
        jPanel1.add(TxtNameClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, 30));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Product Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));
        jPanel1.add(TxtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 120, 30));

        AddButn.setText("Cancel");
        AddButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn.setkBorderRadius(50);
        AddButn.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButnActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, -1));

        AddButn1.setText("Add Order");
        AddButn1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn1.setkBorderRadius(50);
        AddButn1.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn1.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn1.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButn1ActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Price");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        totallbl.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        totallbl.setForeground(new java.awt.Color(204, 0, 102));
        jPanel1.add(totallbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, -1, -1));

        jLabel18.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Quantity");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        jPanel1.add(TxtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 120, 30));

        jLabel19.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Date");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        jLabel20.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Total");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1150, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x= jTable1.getSelectedRow();
        if(x == -1){
            JOptionPane.showMessageDialog(this,
                "Select row please !",
                "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{
            String NameCl = (String) jTable1.getValueAt(x, 1);
            TxtNameClient.setText(NameCl);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void productListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseClicked
        int x= productList.getSelectedRow();
        if(x == -1){
            JOptionPane.showMessageDialog(this,
                "Select row please !",
                "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{

            int id = Integer.parseInt(""+productList.getValueAt(x, 0));
            String Name = (String) productList.getValueAt(x, 1);
            Float price = Float.parseFloat(""+productList.getValueAt(x, 4));
            
            TxtProductName.setText(Name);
            TxtPrice.setText(String.valueOf(price));

          
        }
        
    }//GEN-LAST:event_productListMouseClicked
    public void total()
    {  if(!TxtQuantity.getText().isEmpty()){
        totallbl.setText(String.valueOf(Float.valueOf(TxtPrice.getText()) * Integer.valueOf(TxtQuantity.getText())));
    }else
    {
        totallbl.setText("Please specify the quantity needed ! ");
    }}
              
            
           
            
    private void AddButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButnActionPerformed
       refresh();     
    }//GEN-LAST:event_AddButnActionPerformed

    private void AddButn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButn1ActionPerformed
        Product product = new Product ();
        int x= productList.getSelectedRow();
        int id = Integer.parseInt(""+productList.getValueAt(x, 0));
        int qte = Integer.parseInt(""+productList.getValueAt(x, 3));
        String Name = (String) productList.getValueAt(x, 1);
        Float price = Float.parseFloat(""+productList.getValueAt(x, 4));
        String cat = (String) productList.getValueAt(x, 2);
        System.out.println( qte);
        
        
        Order order = new Order();
        if (TxtNameClient.getText().isEmpty()||TxtQuantity.getText().isEmpty()||TxtPrice.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Missing Informations ! Please Select a product or client and Enter the Quantity");
           
       }else
          {
        
        order.setPrice (Float.valueOf(TxtPrice.getText()));
        order.setTotal (order.getPrice() * Integer.valueOf(TxtQuantity.getText()));
        order.setNamePro(TxtProductName.getText());
        order.setNameCl(TxtNameClient.getText());
        order.setQte(Integer.valueOf(TxtQuantity.getText()));
        order.setDate(datelbl.getText());
        if (order.getQte()> qte)
        {
            JOptionPane.showMessageDialog(this, "You don't have enough quantity in stock for this order ! ");
            refresh();
        }
        else{
        boolean result = new OrderController().create(order);
       
       if(result){              
            JOptionPane.showMessageDialog(this,
            order.getId()+" Is successfuly added  ",
            "New Order", JOptionPane.INFORMATION_MESSAGE);
            //new userList().setVisible(true);
            ShowOrders orders = new ShowOrders();
                     ArrayList<Order>  myorderlist = new OrderController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    orders.OrdersList.setModel(model) ; 
                    model.addColumn("Id");
                    model.addColumn("NameProduct");
                    model.addColumn("NameClient");
                    model.addColumn("Quantity");
                    model.addColumn("Price");
                    model.addColumn("Total");
                    model.addColumn("Date");

                    for (Order u : myorderlist) {            
                        Object[] row =   new Object[]{u.getId(), u.getNamePro(), u.getNameCl(), u.getQte(), u.getPrice(),u.getTotal(),u.getDate() };
                        model.addRow(  row);
                    }
                    orders.OrdersList.setModel(model);
            refresh();
            
        }    
        ////////////////////////////////////////////////////////////////////////////////////
        
        System.out.println( qte-order.getQte());
        
       
        product.setQte (qte-order.getQte());
        product.setNamePro(Name);
        product.setCategorie(cat);
        product.setPrice(price);
       
        boolean result1 = new ProductController().update(id, product);
         if(result1){              
            
            JOptionPane.showMessageDialog(this,
            product.getNamePro().toUpperCase()+" est modifié avec success ",
            "Modifier utilisateur", JOptionPane.INFORMATION_MESSAGE);
            
                    ArrayList<Product>  myproductlist = new ProductController().retrieveAll();
                    DefaultTableModel model1 = new DefaultTableModel() ;
                    productList.setModel(model1) ; 
                    model1.addColumn("IdPro");
                    model1.addColumn("NamePro");
                    model1.addColumn("CategoryPro");
                    model1.addColumn("QuantityPro");
                    model1.addColumn("PricePro");

                    for (Product pr : myproductlist) {            
                        Object[] row =   new Object[]{pr.getIdPro(), pr.getNamePro(), pr.getCategorie(), pr.getQte(), pr.getPrice() };
                        model1.addRow(row);
                    }
                    productList.setModel(model1);
         }}}
        
    }//GEN-LAST:event_AddButn1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        total();
    }//GEN-LAST:event_jLabel20MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddButn;
    private com.k33ptoo.components.KButton AddButn1;
    private javax.swing.JTextField TxtNameClient;
    private javax.swing.JTextField TxtOrderId;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtProductName;
    private javax.swing.JTextField TxtQuantity;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTable productList;
    private javax.swing.JLabel totallbl;
    // End of variables declaration//GEN-END:variables

   
}
