/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoryController;

import Model.Category;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iyed
 */
public class ShowCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowCategory
     */
    public ShowCategory() {
        initComponents();
        TxtIdCat.setEditable(false);
        ArrayList<Category>  mycategorylist = new CategoryController().retrieveAll();
        DefaultTableModel model = new DefaultTableModel() ;
        jTable1.setModel(model) ; 
        model.addColumn("IdCat");
        model.addColumn("NameCat");
      

        for (Category c  : mycategorylist) {            
            Object[] row =   new Object[]{c.getIdCat(), c.getNameCat()};
            model.addRow(  row);
        }
        jTable1.setModel(model);
    }
    public void refresh()
    {
        TxtIdCat.setText("");
        TxtNameCat.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        Txtsearch = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        TxtIdCat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtNameCat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AddButn = new com.k33ptoo.components.KButton();
        DeleteButn = new com.k33ptoo.components.KButton();
        ModifyButn = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(900);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 95, 134));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtsearch.setBackground(new Color (0,0,0,0));
        Txtsearch.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        Txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        Txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Txtsearch.setOpaque(false);
        kGradientPanel1.add(Txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 310, 33));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/search.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        kGradientPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/menu_dopkdileye44_64.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, -1, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 0, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 560, 360));

        kGradientPanel2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        kGradientPanel2.setkBorderRadius(50);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtIdCat.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TxtIdCat.setForeground(new java.awt.Color(204, 0, 102));
        TxtIdCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdCatActionPerformed(evt);
            }
        });
        kGradientPanel2.add(TxtIdCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 30));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("NAME : ");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        TxtNameCat.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TxtNameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameCatActionPerformed(evt);
            }
        });
        kGradientPanel2.add(TxtNameCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 30));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("ID : ");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 360, 220));

        AddButn.setText("Add New Category");
        AddButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        AddButn.setkBorderRadius(50);
        AddButn.setkEndColor(new java.awt.Color(102, 204, 255));
        AddButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        AddButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        AddButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButnActionPerformed(evt);
            }
        });
        jPanel1.add(AddButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, -1, -1));

        DeleteButn.setText("Delete Category");
        DeleteButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        DeleteButn.setkBorderRadius(50);
        DeleteButn.setkEndColor(new java.awt.Color(102, 204, 255));
        DeleteButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        DeleteButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        DeleteButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, -1, -1));

        ModifyButn.setText("Modify Category");
        ModifyButn.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ModifyButn.setkBorderRadius(50);
        ModifyButn.setkEndColor(new java.awt.Color(102, 204, 255));
        ModifyButn.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        ModifyButn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ModifyButn.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        ModifyButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButnActionPerformed(evt);
            }
        });
        jPanel1.add(ModifyButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/edit_wgcm8dcqn62n_32 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/delete_nlu06yttn93n_32 (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/new_c9ip5vbgk3tm_32 (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 40, 50));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Categories List");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
    String keyword= Txtsearch.getText();
        ArrayList<Category>  mycategorylist = new CategoryController().retrieveByKeyWord(keyword);
        DefaultTableModel model = new DefaultTableModel() ;
        jTable1.setModel(model) ; 
        model.addColumn("IdCat");
        model.addColumn("NameCat");
       


        for (Category c : mycategorylist) {            
            Object[] row =   new Object[]{c.getIdCat(), c.getNameCat() };
            model.addRow(  row);
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_SearchMouseClicked

    private void TxtIdCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdCatActionPerformed

    private void TxtNameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameCatActionPerformed

    private void AddButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButnActionPerformed
        Category category = new Category();
        category.setNameCat(TxtNameCat.getText());
      
 
        boolean result = new CategoryController().create(category);
        
         if(result){              
            JOptionPane.showMessageDialog(this,
            category.getNameCat().toUpperCase()+" Is successfuly added  ",
            "New Category", JOptionPane.INFORMATION_MESSAGE);
           
                    ArrayList<Category>  mycategorylist = new CategoryController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("IdCat");
                    model.addColumn("NameCat");
                    

                    for (Category c : mycategorylist) {            
                        Object[] row =   new Object[]{c.getIdCat(), c.getNameCat() };
                        model.addRow(row);
                    }
                    jTable1.setModel(model);
            
            
            
            
        }else{          
            JOptionPane.showMessageDialog(this,
            "Ajout erronée ",
            "Nouvelle Categorie", JOptionPane.ERROR_MESSAGE);
        }
         refresh();
    }//GEN-LAST:event_AddButnActionPerformed

    private void DeleteButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButnActionPerformed
       int x= jTable1.getSelectedRow();
        if(x == -1){
             JOptionPane.showMessageDialog(this,
            "Select row please !",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{
            int p=  JOptionPane.showConfirmDialog(this,
            "Confirm to delete row number : "+ (x+1),
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
             System.out.println(p);
             if (p == 0){
                 int id =  Integer.parseInt(""+jTable1.getValueAt(x, 0));
                 System.out.println(id);
                 if(new CategoryController().delete(id)){
                      JOptionPane.showMessageDialog(this,
            "Category Deleted with success!",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
                      
                      
                    ArrayList<Category>  mycategorylist = new CategoryController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("IdCat");
                    model.addColumn("NameCat");


                    for (Category c : mycategorylist) {            
                        Object[] row =   new Object[]{c.getIdCat(), c.getNameCat() };
                        model.addRow(  row);
                    }
                    jTable1.setModel(model);

                    
                      
                      
                 } else{
                      JOptionPane.showMessageDialog(this,
            "Category not Deleted check with the administrator!",
            "Error Message", JOptionPane.ERROR_MESSAGE);
                 }
                 
             }
               
        } refresh();
    }//GEN-LAST:event_DeleteButnActionPerformed

    private void ModifyButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButnActionPerformed
       Category category = new Category();
        category.setNameCat(TxtNameCat.getText());
        
 
        
        int id = Integer.parseInt(""+ TxtIdCat.getText());
        boolean result = new CategoryController().update(id, category);
        
         if(result){              
            JOptionPane.showMessageDialog(this,
            category.getNameCat().toUpperCase()+" est modifié avec success ",
            "Modifier utilisateur", JOptionPane.INFORMATION_MESSAGE);
            //new userList().setVisible(true);
                    ArrayList<Category>  mycategorylist = new CategoryController().retrieveAll();
                    DefaultTableModel model = new DefaultTableModel() ;
                    jTable1.setModel(model) ; 
                    model.addColumn("IdCat");
                    model.addColumn("NameCat");
               

                    for (Category c : mycategorylist) {            
                        Object[] row =   new Object[]{c.getIdCat(), c.getNameCat() };
                        model.addRow(  row);
                    }
                    jTable1.setModel(model);
          
        }else{          
            JOptionPane.showMessageDialog(this,
            "Modification erronée ",
            "Modifier categorie", JOptionPane.ERROR_MESSAGE);
        }
         refresh();
    }//GEN-LAST:event_ModifyButnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                int x= jTable1.getSelectedRow();
        if(x == -1){
             JOptionPane.showMessageDialog(this,
            "Select row please !",
            "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else{

                int id = Integer.parseInt(""+jTable1.getValueAt(x, 0));
                String NameCat = (String) jTable1.getValueAt(x, 1);
              
                 TxtIdCat.setText(String.valueOf(id));
                 TxtIdCat.setEnabled(false);
                 TxtNameCat.setText(NameCat);
                
                

              }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddButn;
    private com.k33ptoo.components.KButton DeleteButn;
    private com.k33ptoo.components.KButton ModifyButn;
    private javax.swing.JLabel Search;
    private javax.swing.JTextField TxtIdCat;
    private javax.swing.JTextField TxtNameCat;
    private javax.swing.JTextField Txtsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
